### ISSUE TITLE
Align dashboard menu options to the left

### ISSUE THREAD

**Issue by Caelebs** [apache/apisix-dashboard#1335]
# Bug report

## Describe the bug

I deployed the latest version of dashboard v2.3, and found that the `Server Info` in the left menu bar is not aligned, and the icons and text titles are displayed misaligned. And the content displayed in the `Server Info` is not very friendly. I hope that `last_report_time ` and `boot_time` do not use Unix Timestamp to display. In addition, the etcd version number obtained by `etcd_version` is not exactly the same as the actual version number used.

## Screenshots

![20210120104337](https://user-images.githubusercontent.com/12752710/105120578-7294f800-5b0d-11eb-86df-84231f5e406f.png)
![20210120104404](https://user-images.githubusercontent.com/12752710/105120585-74f75200-5b0d-11eb-9cf4-d1086d76f3a4.png)
![20210120110241](https://user-images.githubusercontent.com/12752710/105121632-8c373f00-5b0f-11eb-9a39-63179a391f21.png)

## System information

- OS: `CentOS Linux release 7.7.1908 (Core)`
- Browser: `Chrome/78.0.3904.108`
- Version: `apisix-dashboard-2.3`

**Comment by KishaniKandasamy** [comment]
Hi I think  I fixed " Align dashboard menu options to the left".
![Screenshot (34)](https://user-images.githubusercontent.com/53715187/105181034-4c914700-5b51-11eb-98b5-a7bd3b6207ab.png)

**Comment by KishaniKandasamy** [comment]
but here,I think  the Server Info is already in a form of human readable.
![Screenshot (35)](https://user-images.githubusercontent.com/53715187/105181233-89f5d480-5b51-11eb-9352-a98dc15dec10.png)

**Comment by juzhiyuan** [comment]
@nic-chen Please take a look at this issue, the etcd version is incorrect according to user's feedback 🤔

**Comment by Caelebs** [comment]
![image](https://user-images.githubusercontent.com/12752710/112435844-3afe3280-8d80-11eb-8ed8-c4e22660e85f.png)
![image](https://user-images.githubusercontent.com/12752710/112436123-916b7100-8d80-11eb-860f-21c359296ef9.png)

I just built the dashboard of version 2.5, and found that this item is still not aligned. Is the code merging missing?
Browser version: Google Chrome | 87.0.4280.66 (正式版本) （64 位） (cohort: 87_66_Win)

@juzhiyuan @KishaniKandasamy

**Comment by juzhiyuan** [comment]
🤔 not sure, let me reopen this.

**Comment by nic-chen** [comment]
@Caelebs 
Is there still a problem with the wrong etcd version?

**Comment by juzhiyuan** [comment]
@nic-chen Hi, this is is a UI issue :)

**Comment by Caelebs** [comment]
I just deployed the latest v2.7 version of the dashboard, and found that this does not seem to be fixed? Is it missed?
![image](https://user-images.githubusercontent.com/12752710/122169244-c5ea5700-ceaf-11eb-9539-01f401710cd2.png)
![image](https://user-images.githubusercontent.com/12752710/122169293-d569a000-ceaf-11eb-88ed-d257e1938d1f.png)

@juzhiyuan

**Comment by juzhiyuan** [comment]
Not sure, please take a look :)

**Comment by iamayushdas** [comment]
Having a look to it

**Comment by iamayushdas** [comment]
@Caelebs @juzhiyuan its not fixed yet, i checked in my env too

**Comment by juzhiyuan** [comment]
good, keep it as Good first issue

**Comment by liuxiran** [comment]
close via #2051 , feel free to reopen it when there are any questions, thanks

**Comment by Caelebs** [comment]
@juzhiyuan
